
server:
  port: 8080
  
spring:
  redis:
    # master: mymaster
    password: mypassword
    sentinel:
      master: mymaster
      nodes: 192.168.1.56:7000,192.168.1.56:7001,192.168.1.56:7002
    #   host: 192.168.1.56
    #   port1: 7000
    #   port2: 7001
    #   port3: 7002
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
  session:
    timeout: 1m
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session